/* Generated by MyraPad at 2024/5/12 15:57:55 */

using System;
using System.Collections.Generic;
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace BazaarBounty
{
	partial class FruitsWidget: Panel
	{
		private void BuildUI(List<Buff> buffs)
		{
			var titleLabel = new Label();
			titleLabel.Text = "Please select a fruit";
			titleLabel.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft80_outline.fnt");
			titleLabel.Margin = new Thickness(0, 0, 0, 680);
			titleLabel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			titleLabel.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			for (int i = 0; i < buffs.Count; i++)
			{
				var buff = buffs[i];
				var fruitsPanel = new VerticalStackPanel();

                var fruitName_splits = buff.BuffName.Split();

				var button = new Button();
				button.PressedBackground = fruitName_splits.Length == 1 ? new SolidBrush("#1A4A21FF") : new SolidBrush("#66B3FFFF");//new SolidBrush("#FF8000FF");
				button.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
				button.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
				button.Background = fruitName_splits.Length == 1 ? new SolidBrush("#4BD961FF") : new SolidBrush("#0080FFFF"); //new SolidBrush("#FFDC35FF");
				button.OverBackground = fruitName_splits.Length == 1 ? new SolidBrush("#308A3EFF") : new SolidBrush("#0066CCFF"); //new SolidBrush("#FFAF60FF");

				var fruitLabel = new Label();
				fruitLabel.Text = buff.BuffName;
				fruitLabel.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft48.fnt");
				fruitLabel.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
				fruitLabel.Margin = new Thickness(0, 20, 0, 0);
				fruitLabel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
				fruitsPanel.Widgets.Add(fruitLabel);

				var fruitIcon = new Image();
                string fruitName = buff.BuffName.Split()[0];
				fruitIcon.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion($"images/fruits/{fruitName}2.png");
				fruitIcon.Width = 64;
				fruitIcon.Height = 74;
				fruitIcon.Margin = new Thickness(0, 10, 0, 0);
				fruitIcon.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
				fruitsPanel.Widgets.Add(fruitIcon);

				var fruitDescription = new Label();
				fruitDescription.Text = buff.BuffDescription;
				fruitDescription.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft24.fnt");
				fruitDescription.Wrap = true;
				fruitDescription.Margin = new Thickness(15, 20);
				fruitsPanel.Widgets.Add(fruitDescription);

				Label fruitDuration = new Label();
				if (!buff.IsPermanent)
				{
					fruitDuration.Text = $"Duration: {buff.Duration}s";
					fruitDuration.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft24.fnt");
					fruitDuration.Wrap = true;
					fruitDuration.TextColor = ColorStorage.CreateColor(255, 204, 1, 255);
					fruitDuration.Margin = new Thickness(15, 10, 15, 20);
				}
				fruitsPanel.Widgets.Add(fruitDuration);

				var confirmIcon = new Image();
				confirmIcon.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("images/icons/A.png");
				confirmIcon.Width = 48;
				confirmIcon.Height = 58;
				confirmIcon.Margin = new Thickness(0, 0, 0, 10);
				confirmIcon.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
				confirmIcon.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
				confirmIcon.Visible = false ; // by default, the confirm icon is hidden
				StackPanel.SetProportionType(confirmIcon, Myra.Graphics2D.UI.ProportionType.Fill);
				fruitsPanel.Widgets.Add(confirmIcon);

				var fruitsPanelWrapper = new Panel();
				fruitsPanelWrapper.Width = 300;
				fruitsPanelWrapper.Height = 500;
				fruitsPanelWrapper.Margin = new Thickness(10, 0);
				fruitsPanelWrapper.Widgets.Add(button);
				fruitsPanelWrapper.Widgets.Add(fruitsPanel);
				fruitsPanelWrapper.Background = new SolidBrush("#4BD961FF");

				horizontalStackPanel1.Widgets.Add(fruitsPanelWrapper);

				buttons.Add(button);
				fruitsPanels.Add(fruitsPanel);
				selectionMaps.Add(button, buff);
				confirmIconMap.Add(button, confirmIcon);
			}

			Widgets.Add(titleLabel);
			Widgets.Add(horizontalStackPanel1);
		}

		private List<Button> buttons = new();
		private List<VerticalStackPanel> fruitsPanels = new();
		private Dictionary<Button, Buff> selectionMaps = new();
		private Dictionary<Button, Image> confirmIconMap = new();
	}
}
