/* Generated by MyraPad at 2024/4/13 22:35:39 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;
using System.Collections.Generic;


#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace BazaarBounty
{
	partial class MenuWidget : Panel
	{
		protected void BuildUI(int numOptions)
		{
			_backgroundImageSlot = new Image();
			if (backgroundImagePath == null)
			{
				backgroundImagePath = "images/bg_main.png"; // default background image
			}
			_backgroundImageSlot.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion(backgroundImagePath);
			_backgroundImageSlot.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_backgroundImageSlot.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;

			_titleLabel = new Label();
			_titleLabel.Text = "Title";
			_titleLabel.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft80_outline.fnt");
			_titleLabel.Margin = new Thickness(0, 200, 0, 0);
			_titleLabel.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_titleLabel.Background = new SolidBrush("#00000000");

			_arrowImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("images/arrow.png");
			_transparentImage = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("images/transparent.png");

			_mainMenu = new VerticalMenu();
			_mainMenu.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_mainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			_mainMenu.LabelFont = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft48.fnt");
			_mainMenu.SelectionHoverBackground = new SolidBrush("#696969FF");
			_mainMenu.SelectionBackground = new SolidBrush("#B59100FF");
			_mainMenu.LabelHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_mainMenu.HoverIndexCanBeNull = false;
			_mainMenu.Width = 350;
			_mainMenu.Border = new SolidBrush("#2A7836FF");
			_mainMenu.BorderThickness = new Thickness(6);
			_mainMenu.Padding = new Thickness(0, 5);
			_mainMenu.Background = new SolidBrush("#212121A4");
			_mainMenu.Id = "_mainMenu";

			_menuItems = new List<MenuItem>();
			for (int i = 0; i < numOptions; i++)
			{
				MenuItem menuItem = new MenuItem();
				menuItem.Text = "Option " + i;
				menuItem.Image = _transparentImage;
				menuItem.Id = "_menuItem" + i;
				_menuItems.Add(menuItem);
				_mainMenu.Items.Add(menuItem);
			}
			
			var image11 = new Image();
			image11.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("images/icons/leftstick.png");
			image11.Width = 48;
			image11.Height = 48;
			image11.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetRow(image11, 0);

			var label7 = new Label();
			label7.Text = "Select";
			label7.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft24.fnt");
			label7.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
			label7.Height = 16;
			label7.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label7.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetColumn(label7, 1);
			Grid.SetRow(label7, 0);

			var image12 = new Image();
			image12.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("images/icons/A.png");
			image12.Width = 48;
			image12.Height = 48;
			image12.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetRow(image12, 1);

			var label8 = new Label();
			label8.Text = "Confirm";
			label8.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft24.fnt");
			label8.TextAlign = FontStashSharp.RichText.TextHorizontalAlignment.Center;
			label8.Height = 16;
			label8.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			label8.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetColumn(label8, 1);
			Grid.SetRow(label8, 1);


			var grid2 = new Grid();
			grid2.ColumnSpacing = 8;
			grid2.DefaultColumnProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid2.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			grid2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			grid2.Margin = new Thickness(0, 0, 20, 10);
			grid2.Widgets.Add(image11);
			grid2.Widgets.Add(label7);
			grid2.Widgets.Add(image12);
			grid2.Widgets.Add(label8);

			Widgets.Add(_backgroundImageSlot);
			Widgets.Add(_titleLabel);
			Widgets.Add(_mainMenu);
			Widgets.Add(grid2);
		}

		public string backgroundImagePath;
		public IImage _arrowImage;
		public IImage _transparentImage;
		public Image _backgroundImageSlot;
		public Label _titleLabel;
		public List<MenuItem> _menuItems;
		public VerticalMenu _mainMenu;
	}
}
