using Microsoft.Xna.Framework.Input;
using Myra.Graphics2D.UI;
using System;

/* Generated by MyraPad at 2024/4/13 17:13:52 */
namespace BazaarBounty
{
    public partial class MenuWidget : IWidgetBase
    {
        int? lastIndex;
        public MenuWidget()
        {
            BuildUI(0);
        }

        public void Initialize()
        {
            _mainMenu.HoverIndex = 0;
            MenuItem menuItem = _menuItems[0];
            if (menuItem != null) menuItem.Image = _arrowImage;

            InputRouter.RegisterInput(Buttons.LeftThumbstickUp, MoveUp, true);
            InputRouter.RegisterInput(Buttons.LeftThumbstickDown, MoveDown, true);
            InputRouter.RegisterInput(Buttons.A, Confirm, true);
        }

        public void Deinitialize()
        {
            InputRouter.DeregisterInput(Buttons.LeftThumbstickUp, MoveUp, true);
            InputRouter.DeregisterInput(Buttons.LeftThumbstickDown, MoveDown, true);
            InputRouter.DeregisterInput(Buttons.A, Confirm, true);
        }

        public void Update()
        {
            if (InputRouter.inputType == InputRouter.InputType.GamePad)
            {
                // Do not update since call HoverIndex may cause change of HoverIndex according to mouse position
                return;
            }
            if (_mainMenu.HoverIndex != lastIndex)
            {
                if (lastIndex != null)
                {
                    MenuItem lastMenuItem = (MenuItem)_mainMenu.Items[(int)lastIndex];
                    lastMenuItem.Image = _transparentImage;
                }
                
                if (_mainMenu.HoverIndex != null)
                {
                    MenuItem menuItem = (MenuItem)_mainMenu.Items[(int)_mainMenu.HoverIndex];
                    menuItem.Image = _arrowImage;
                }

                lastIndex = _mainMenu.HoverIndex;
            }
        }

        private void MoveUp()
        {
            int nextIndex = _mainMenu.HoverIndex - 1 ?? 0;
            nextIndex = nextIndex < 0 ? _mainMenu.Items.Count - 1 : nextIndex;
            if (lastIndex != null) ((MenuItem)_mainMenu.Items[(int)lastIndex]).Image = _transparentImage;
            ((MenuItem)_mainMenu.Items[nextIndex]).Image = _arrowImage;
            lastIndex = nextIndex;
            _mainMenu.HoverIndex = nextIndex;
        }

        private void MoveDown()
        {
            int nextIndex = _mainMenu.HoverIndex + 1 ?? 0;
            nextIndex = nextIndex >= _mainMenu.Items.Count ? 0 : nextIndex;
            if (lastIndex != null) ((MenuItem)_mainMenu.Items[(int)lastIndex]).Image = _transparentImage;
            ((MenuItem)_mainMenu.Items[nextIndex]).Image = _arrowImage;
            lastIndex = nextIndex;
            _mainMenu.HoverIndex = nextIndex;
        }

        private void Confirm()
        {
            int index = _mainMenu.HoverIndex ?? 0;
            MenuItem menuItem = (MenuItem)_mainMenu.Items[index];
            menuItem.FireSelected();
        }
    }

    public class MainMenuWidget : MenuWidget
    {
        public MainMenuWidget()
        {
            backgroundImagePath = "images/bg_main.png";
            BuildUI(2);

            _titleLabel.Text = "Bazaar Bounty";
            _menuItems[0].Text = "New Game";
            _menuItems[1].Text = "Quit";

            _menuItems[1].Selected += (s, a) => BazaarBountyGame.GetGameInstance().Exit();
            _menuItems[0].Selected += (s, a) =>
            {
                var uiManager = BazaarBountyGame.uiManager;
                uiManager.RemoveWidget(uiManager.MainMenu);
                uiManager.AddWidget(uiManager.TutorialWidget);
            };
        }
    }

    public class GameEndWidget : MenuWidget
    {
        public GameEndWidget()
        {
            backgroundImagePath = "images/bg_lose.png";
            BuildUI(2);
            
            _titleLabel.Text = "Game Over";
            _menuItems[0].Text = "Restart";
            _menuItems[1].Text = "Quit";

            _menuItems[1].Selected += (s, a) => BazaarBountyGame.GetGameInstance().Exit();
            _menuItems[0].Selected += (s, a) =>
            {
                var uiManager = BazaarBountyGame.uiManager;
                uiManager.RemoveWidget(uiManager.EndWidget);
                uiManager.AddWidget(uiManager.MainMenu);
                BazaarBountyGame.GetGameInstance().ResetGame();
            };
        }
    }

    public class GameWinWidget : MenuWidget
    {
        public GameWinWidget()
        {
            backgroundImagePath = "images/bg_win.png";
            BuildUI(2);

            _titleLabel.Text = "You Win!";
            _menuItems[0].Text = "Restart";
            _menuItems[1].Text = "Quit";

            _menuItems[1].Selected += (s, a) => BazaarBountyGame.GetGameInstance().Exit();
            _menuItems[0].Selected += (s, a) =>
            {
                var uiManager = BazaarBountyGame.uiManager;
                uiManager.RemoveWidget(uiManager.WinWidget);
                uiManager.AddWidget(uiManager.MainMenu);
                BazaarBountyGame.GetGameInstance().ResetGame();
            };
        }
    }
}