/* Generated by MyraPad at 2024/5/9 15:34:53 */

using Microsoft.Xna.Framework.Input;

namespace BazaarBounty
{
	public partial class TutorialWidget : IWidgetBase
	{
		public TutorialWidget()
		{
			BuildUI();
		}
		
		public void Initialize()
		{
			InputRouter.RegisterInput(Buttons.A, Continue, true);
			InputRouter.mouseLeftButtonHandler += Continue;
		}
		
		public void Deinitialize()
		{
			InputRouter.DeregisterInput(Buttons.A, Continue, true);
			InputRouter.mouseLeftButtonHandler -= Continue;
		}

		private void Continue()
		{
			var uiManager = BazaarBountyGame.uiManager;
			uiManager.RemoveWidget(uiManager.TutorialWidget);
			BazaarBountyGame.GetGameInstance().StartNewGame();
		}
	}
}