/* Generated by MyraPad at 2024/5/9 15:34:53 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;
using Microsoft.Xna.Framework.Input;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace BazaarBounty
{
	partial class TutorialWidget: Panel
	{
		private void BuildUI()
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("images/bg_main.png");
			image1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			image1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;

			_tutorialPanel = new Panel();
			_tutorialPanel.Opacity = 0.9f;
			_tutorialPanel.Background = new SolidBrush("#2A7836FF");

			var textBox1 = new TextBox();
			textBox1.Text = "Tutorial";
			textBox1.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft48.fnt");
			textBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textBox1.Margin = new Thickness(20, 20, 20, 5);
			textBox1.Background = new SolidBrush("#00000000");

			var textBox2 = new TextBox();
			textBox2.Text = "Your goal is to defeat all the enemies in each level to save the bazaar. (20 leve" +
    "ls)";
			textBox2.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft24.fnt");
			textBox2.Margin = new Thickness(20, 20, 20, 5);
			textBox2.Background = new SolidBrush("#00000000");

			var textBox3 = new TextBox();
			textBox3.Text = "You can attack with a sword and shoot with a gun.";
			textBox3.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft24.fnt");
			textBox3.Margin = new Thickness(20, 5);
			textBox3.Background = new SolidBrush("#00000000");

			var textBox4 = new TextBox();
			textBox4.Text = "Clear levels to obtain fruit buffs from enemies to strengthen youself!";
			textBox4.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft24.fnt");
			textBox4.Margin = new Thickness(20, 5);
			textBox4.Background = new SolidBrush("#00000000");

			var textBox5 = new TextBox();
			textBox5.Text = "Hint:";
			textBox5.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft32.fnt");
			textBox5.TextColor = ColorStorage.CreateColor(254, 57, 48, 255);
			textBox5.Margin = new Thickness(20, 5);
			textBox5.Background = new SolidBrush("#00000000");

			var textBox6 = new TextBox();
			textBox6.Text = "Swing your sword at the right time to deflect bullets from enemies!";
			textBox6.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft24.fnt");
			textBox6.TextColor = ColorStorage.CreateColor(254, 57, 48, 255);
			textBox6.Margin = new Thickness(20, 5);
			textBox6.Background = new SolidBrush("#00000000");

			var image2 = new Image();
			image2.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("images/controller.png");
			image2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			image2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			var image3 = new Image();
			image3.Renderable = MyraEnvironment.DefaultAssetManager.LoadTextureRegion("images/icons/A.png");
			image3.Width = 54;
			image3.Height = 48;
			image3.Margin = new Thickness(0, 0, 8, 0);

			var textBox7 = new TextBox();
			textBox7.Text = "Continue";
			textBox7.Font = MyraEnvironment.DefaultAssetManager.LoadFont("fonts/Minecraft32.fnt");
			textBox7.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			textBox7.Background = new SolidBrush("#00000000");

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			horizontalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			horizontalStackPanel1.Margin = new Thickness(20, 0, 20, 20);
			horizontalStackPanel1.Widgets.Add(image3);
			horizontalStackPanel1.Widgets.Add(textBox7);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(textBox1);
			verticalStackPanel1.Widgets.Add(textBox2);
			verticalStackPanel1.Widgets.Add(textBox3);
			verticalStackPanel1.Widgets.Add(textBox4);
			verticalStackPanel1.Widgets.Add(textBox5);
			verticalStackPanel1.Widgets.Add(textBox6);
			verticalStackPanel1.Widgets.Add(image2);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);

			var panel2 = new Panel();
			panel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			panel2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			panel2.Widgets.Add(_tutorialPanel);
			panel2.Widgets.Add(verticalStackPanel1);

			Widgets.Add(image1);
			Widgets.Add(panel2);
		}

		private Panel _tutorialPanel;
	}
}
